module.exports = {
    CONNECTION: {
        NO_NETWORK: 'CONNECTION_NO_NETWORK',
        UNABLE_TO_RESOLVE: 'CONNECTION_NO_RESOLVE',
        TIMEOUT: 'CONNECTION_TIMEOUT',
        NOT_FOUND: 'CONNECTION_NOT_FOUND',
        NO_CACHE: 'CONNECTION_NO_CACHE_AVAILABLE'
    },
    PROXER : {
        OFFLINE: 'PROXER_OFFLINE',
        INVALID_CREDENTIALS: 'PROXER_INVALID_CREDENTIALS',
        NO_DETAILS_PROVIDED: 'PROXER_NO_DETAILS',
        MYSQL_DOWN: 'PROXER_MYSQL_ERROR',
        CLOUDFLARE: 'PROXER_CLOUDFLARE_PROTECTION'
    },
    OTHER: {
        UNKNOWN: 'UNKNOWN_ERROR'
    },
    SEVERITY: {
        SEVERE: 'severe',
        WARNING: 'warn',
        INFO: 'info'
    }
};