module.exports = {
    CONNECTION: {
        NO_NETWORK: 'ERROR.CONNECTION_NO_NETWORK',
        UNABLE_TO_RESOLVE: 'ERROR.CONNECTION_NO_RESOLVE',
        TIMEOUT: 'ERROR.CONNECTION_TIMEOUT',
        NOT_FOUND: 'ERROR.CONNECTION_NOT_FOUND',
        NO_CACHE: 'ERROR.CONNECTION_NO_CACHE_AVAILABLE',
        NETWORK_RECONNECT: 'ERROR.CONNECTION_RECONNECT'
    },
    PROXER : {
        OFFLINE: 'ERROR.PROXER_OFFLINE',
        INVALID_CREDENTIALS: 'ERROR.PROXER_INVALID_CREDENTIALS',
        NO_DETAILS_PROVIDED: 'ERROR.PROXER_NO_DETAILS',
        MYSQL_DOWN: 'ERROR.PROXER_MYSQL_ERROR',
        CLOUDFLARE: 'ERROR.PROXER_CLOUDFLARE_PROTECTION',
        API_LIMIT_REACHED: 'ERROR.PROXER_API_LIMIT'
    },
    STREAMS: {
        CANNOT_PARSE: 'ERROR.STREAM_NO_PARSER'
    },
    OTHER: {
        UNKNOWN: 'ERROR.UNKNOWN_ERROR',
        CACHE_CLEAR: 'ERROR.CACHE_CLEAR'
    },
    SEVERITY: {
        SEVERE: 'ERROR_SEVERITY.severe',
        WARNING: 'ERROR_SEVERITY.warn',
        INFO: 'ERROR_SEVERITY.info'
    }
};
