name: CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@722adc63f1aa60a57ec37892e133b1d319cae598
      - uses: actions/setup-node@c35dd24c52f85b8c80fd1619f6bc7b9e82c840db
        with:
          node-version: '10.x'
      - name: Install dependencies
        run: npm ci
      - name: Check compile
        run: npm run dist
